from __future__ import annotations

import uuid

from sqlalchemy import Boolean, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel


class ConfigurationPlan(BaseModel):
    """A named transport configuration (can be generated by optimisation)."""

    __tablename__ = "configuration_plan"
    __table_args__ = (
        Index("ix_configuration_plan_tenant", "tenant_id"),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenant.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, server_default="true", nullable=False)
    is_current: Mapped[bool] = mapped_column(Boolean, server_default="false", nullable=False)
    source: Mapped[str | None] = mapped_column(
        String(50), nullable=True
    )

    rows: Mapped[list[ConfigurationTransport]] = relationship(
        "ConfigurationTransport",
        back_populates="plan",
        cascade="all, delete-orphan",
        lazy="noload",
    )
