from __future__ import annotations

import uuid

from geoalchemy2 import Geometry
from sqlalchemy import Boolean, Float, ForeignKey, Index, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import BaseModel


class GeneratedStop(BaseModel):
    """A candidate stop location generated by DBSCAN or manual entry."""

    __tablename__ = "generated_stop"
    __table_args__ = (
        Index("ix_generated_stop_tenant_id", "tenant_id"),
        Index("ix_generated_stop_site_id", "site_id"),
        Index("ix_generated_stop_geom", "geom", postgresql_using="gist"),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenant.id"), nullable=False
    )
    site_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("site.id"), nullable=True
    )
    ligne_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("ligne.id"), nullable=True
    )

    lat: Mapped[float] = mapped_column(Float, nullable=False)
    lng: Mapped[float] = mapped_column(Float, nullable=False)
    geom: Mapped[object] = mapped_column(
        Geometry(geometry_type="POINT", srid=4326), nullable=True
    )

    catchment_radius_m: Mapped[float] = mapped_column(
        Float, nullable=False, server_default="500"
    )
    demand_passengers: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    berth_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="1"
    )

    capacity_buses_per_hour: Mapped[float | None] = mapped_column(Float, nullable=True)
    capacity_los: Mapped[str | None] = mapped_column(String(1), nullable=True)
    avg_wait_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)

    source: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="dbscan"
    )
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="true"
    )
