"""add employee table

Revision ID: 5870888f28d7
Revises: 6a184bb1915d
Create Date: 2026-04-01 14:13:24.561950
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5870888f28d7'
down_revision: Union[str, None] = '6a184bb1915d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('shift_time', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('quartier', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('preferred_pickup_address', sa.Text(), nullable=True),
    sa.Column('preferred_pickup_lat', sa.Float(), nullable=True),
    sa.Column('preferred_pickup_lng', sa.Float(), nullable=True),
    sa.Column('is_pmr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('function_role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('transport_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('current_transport_mode', sa.String(length=50), nullable=True),
    sa.Column('opt_in_company_transport', sa.String(length=20), server_default='Non', nullable=False),
    sa.Column('has_private_car', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('volunteer_driver', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('carpool_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sirh_external_id', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'matricule', name='uq_employee_tenant_matricule')
    )
    op.create_index('ix_employee_active', 'employee', ['active'], unique=False)
    op.create_index('ix_employee_geom', 'employee', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_employee_site_id', 'employee', ['site_id'], unique=False)
    op.create_index('ix_employee_tenant_id', 'employee', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_tenant_id', table_name='employee')
    op.drop_index('ix_employee_site_id', table_name='employee')
    op.drop_index('ix_employee_geom', table_name='employee', postgresql_using='gist')
    op.drop_index('ix_employee_active', table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
