"""add route table

Revision ID: 62f4c8fa5cd7
Revises: dbe84fb4d94d
Create Date: 2026-04-01 22:09:30.627364
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62f4c8fa5cd7'
down_revision: Union[str, None] = 'dbe84fb4d94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('optimization_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('ordered_stops', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_time_minutes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('rti_compliance_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_id'], ['optimization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: GIST index on geom is auto-created by GeoAlchemy2 during create_table
    op.create_index('idx_route_optimization', 'route', ['optimization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_optimization', table_name='route')
    op.drop_table('route')
    # Note: GIST index on geom is auto-dropped with the table
    # ### end Alembic commands ###
