"""add site table

Revision ID: 6a184bb1915d
Revises: 72f2ddb31929
Create Date: 2026-04-01 13:07:59.786638
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a184bb1915d'
down_revision: Union[str, None] = '72f2ddb31929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('num_shifts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('shift_1_entry', sa.Time(), nullable=True),
    sa.Column('shift_1_exit', sa.Time(), nullable=True),
    sa.Column('shift_2_entry', sa.Time(), nullable=True),
    sa.Column('shift_2_exit', sa.Time(), nullable=True),
    sa.Column('shift_3_entry', sa.Time(), nullable=True),
    sa.Column('shift_3_exit', sa.Time(), nullable=True),
    sa.Column('working_days', sa.String(length=100), server_default='Lundi-Vendredi', nullable=True),
    sa.Column('days_per_week', sa.Integer(), server_default='5', nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('parking_notes', sa.Text(), nullable=True),
    sa.Column('zfe_zone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('security_profile', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Paris', nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_site_geom', 'site', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_site_tenant_id', 'site', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_tenant_id', table_name='site')
    op.drop_index('ix_site_geom', table_name='site', postgresql_using='gist')
    op.drop_table('site')
    # ### end Alembic commands ###
