"""add employee_modal table

Revision ID: 93e4979d00f3
Revises: e7053e5ce269
Create Date: 2026-04-01 17:30:41.007892
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e4979d00f3'
down_revision: Union[str, None] = 'e7053e5ce269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_modal',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('primary_mode', sa.String(length=50), nullable=False),
    sa.Column('alternative_mode', sa.String(length=50), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('travel_time_min', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('interest_company_transport', sa.String(length=30), nullable=True),
    sa.Column('reason_current_mode', sa.Text(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('accepts_common_pickup', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_pickup_distance_meters', sa.Integer(), server_default='500', nullable=False),
    sa.Column('has_private_car', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('volunteer_driver', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('carpool_seats_available', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_detour_minutes', sa.Integer(), nullable=True),
    sa.Column('bonus_opt_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_employee_modal_employee_id')
    )
    op.create_index('idx_modal_employee', 'employee_modal', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_modal_employee', table_name='employee_modal')
    op.drop_table('employee_modal')
    # ### end Alembic commands ###
