"""add_optimization_and_cluster_tables

Revision ID: c372c3416485
Revises: 93e4979d00f3
Create Date: 2026-04-01 18:23:33.509680
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c372c3416485'
down_revision: Union[str, None] = '93e4979d00f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('condition_type', sa.String(length=30), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_optimization_tenant', 'optimization', ['tenant_id'], unique=False)
    op.create_table('cluster',
    sa.Column('optimization_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lng', sa.Float(), nullable=False),
    sa.Column('centroid_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('employee_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pmr_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('security_risk_level', sa.String(length=20), server_default='low', nullable=False),
    sa.Column('employee_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_id'], ['optimization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_optimization', 'cluster', ['optimization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cluster_optimization', table_name='cluster')
    op.drop_table('cluster')
    op.drop_index('idx_optimization_tenant', table_name='optimization')
    op.drop_table('optimization')
    # ### end Alembic commands ###
