"""add_weather_forecast_table

Revision ID: dbc17ef335ab
Revises: 62f4c8fa5cd7
Create Date: 2026-04-01 23:17:14.719256
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc17ef335ab'
down_revision: Union[str, None] = '62f4c8fa5cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('condition_summary', sa.String(length=100), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_kph', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'source', name='uq_weather_site_date_source')
    )
    op.create_index('idx_weather_forecast_site_id', 'weather_forecast', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_forecast_site_id', table_name='weather_forecast')
    op.drop_table('weather_forecast')
    # ### end Alembic commands ###
