"""add_vehicle_table

Revision ID: dbe84fb4d94d
Revises: c372c3416485
Create Date: 2026-04-01 18:43:02.123537
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe84fb4d94d'
down_revision: Union[str, None] = 'c372c3416485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('brand_model', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('monthly_cost_mad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('condition', sa.String(length=20), server_default='Bon', nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('is_pmr_accessible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fuel_consumption', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cost_per_km', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('motorization', sa.String(length=30), nullable=True),
    sa.Column('length_meters', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('zfe_compliant', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_site', 'vehicle', ['site_id'], unique=False)
    op.create_index('idx_vehicle_tenant', 'vehicle', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicle_tenant', table_name='vehicle')
    op.drop_index('idx_vehicle_site', table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
